name: armTemplateDeployment

on: 
# workflow_dispatch:
  push: 
    branches:
      - main
    
jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
      - name: Deploy Resource Group rg-githubactions with AZ CLI
        uses: Azure/cli@v1
        with: 
          inlinescript: |
            az deployment sub create --location "East US" --template-file ./arm-templates/resourcegroup.json --unhandled-rejections=strict`
          
